test

diff --git a/.buildkite/plugins/vault-secrets/hooks/pre-command b/.buildkite/plugins/vault-secrets/hooks/pre-command
--- a/.buildkite/plugins/vault-secrets/hooks/pre-command
+++ b/.buildkite/plugins/vault-secrets/hooks/pre-command
@@ -74,10 +74,11 @@ get_cred() {
     fi
 
     local value
-    if value="$(vault_with_retry kv get -field "$field" "$vault_path" 2>/dev/null)"; then
+    if value="$(vault_with_retry kv get -field "$field" "$vault_path" 2>&1)"; then
         output "export ${env_name}='${value}'"
         return 0
     else
+        echo "❌ Vault error: $value" >&2
         return 1
     fi
 }
@@ -88,10 +89,11 @@ get_json_cred(){
     local env_name="${1}"; shift
 
     local value
-    if value="$(vault_with_retry kv get --format=json "$vault_path" 2>/dev/null)"; then
+    if value="$(vault_with_retry kv get --format=json "$vault_path" 2>&1)"; then
         output "export ${env_name}='${value}'"
         return 0
     else
+        echo "❌ Vault error: $value" >&2
         return 1
     fi
 }
